metadata:
  engine: 4.0.2
  keyboard: Splayer 1
  version: 1.0
  author: Yoragon

units:
  # Proxy spacing variables
  kx: cx
  ky: cy
  # Padding variables
  px: kx + 3
  py: ky + 3
  # Adjusting preview to choc keys
  $default_width: cx
  $default_height: cy

  # Stagger values used in the matrix
  ring_stagger: 2
  matrix_stagger: 5

  # Splay values used in the matrix
  pinky_splay: 10
  ring_splay: -8
  nullify_splay: -(ring_splay+pinky_splay)
  thumb_splay: -12

  # Spread values used in the matrix
  pinky_ring_spread: kx+2
  ring_middle_stagger: kx+1

  # Shift value of the controller
  controller_shift_x: kx+3.25
  controller_shift_y: 10.491
  # Shift value of the battery plug
  battery_shift_x: kx+2.5
  battery_shift_y: -10
  # Shift value of the reset button
  reset_shift_x: kx+12.5
  reset_shift_y: -15
  # Shift value of the slider switch
  slider_shift_x: kx+12.5
  slider_shift_y: -25

points:
  key:
    # Choc spacing
    padding: ky
    spread: kx

  zones:
    # Primary 3x5 key matrix
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      columns:
        pinky:
          key:
            bind: 0
            splay: pinky_splay
          rows:
              top:
                column_net: P2
              home:
                column_net: P6
              bottom:
                column_net: P8

        ring:
          key:
            splay: ring_splay
            spread: pinky_ring_spread
            stagger: ring_stagger
          rows:
            top:
              column_net: P0
            home:
              column_net: P5
            bottom:
              column_net: P7

        middle:
          key:
            stagger: matrix_stagger
            splay: nullify_splay
            spread: ring_middle_stagger
          rows:
            top:
              column_net: P1
            home:
              column_net: P3
            bottom:
              column_net: P4

        index:
          key:
            stagger: -matrix_stagger
          rows:
            top:
              column_net: P21
            home:
              column_net: P19
            bottom:
              column_net: P15

        inner:
          key:
            stagger: -matrix_stagger
          rows:
            top:
              column_net: P20
            home:
              column_net: P18
            bottom:
              column_net: P14

      rows:
        bottom:
        home:
        top:

    # Thumb cluster keys
    thumbs:
      # The thumb cluster is anchored to the bottom left, though it is shifted such that the middle key of the cluster is placed under the inner column of the main matrix
      anchor:
        ref: matrix_inner_bottom
        shift: [-kx-3,-ky]

      columns:
        outer:
          key:
            column_net: P10

        main:
          key:
            bind: [0,0,0,3]
            splay: thumb_splay
            shift: [3,-2]
            column_net: P16

        inner:
          key:
            splay: thumb_splay
            shift: [6,-3]
            column_net: P9

outlines:
  keys_outline:
    - what: rectangle
      where: true
      size: [px, py]
      bound: true

  keys:
    - what: rectangle
      where: true
      size: [kx, ky]

  switch_hole:
    - what: rectangle
      where: true
      size: [13.95, 13.95]

  polygon:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_pinky_top
          shift: [0.5px,0.5py]
        - ref: matrix_inner_top
          shift: [1.55px,0.5py]
        - ref: thumbs_inner
          shift: [0.5px,0.5py]
        - ref: thumbs_outer
          shift: [-0.5px,-0.5py]
        - ref: thumbs_outer
          shift: [-0.5px,0.21py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]

  board:
    - name: keys_outline
    - operation: add
      name: polygon
      fillet: 1.9

  case_top_plate:
    - name: board
    - operation: subtract
      name: switch_hole

pcbs:
  splayer_pcb:
    template: kicad8
    outlines:
      main:
        outline: board

    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          reversible: true
          solder: true
          include_keycap: true
          keycap_height: 17
          include_corner_marks: true
          from: "{{column_net}}"
          to: GND

      controller:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_inner_home
          shift: [controller_shift_x,controller_shift_y]
        params:
          reversible: true
          reverse_mount: true
          only_required_jumpers: true

      battery:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          reversible: true
        where:
          ref: matrix_inner_home
          shift: [battery_shift_x,battery_shift_y]
          rotate: -90

      reset:
        what: ceoloide/reset_switch_smd_side
        params:
          reversible: true
          from: GND
          to: RST
        where:
          ref: matrix_inner_home
          shift: [reset_shift_x,reset_shift_y]
          rotate: -90

      slider:
        what: ceoloide/power_switch_smd_side
        params:
          reversible: true
        where:
          ref: matrix_inner_home
          shift: [slider_shift_x,slider_shift_y]

      via1:
        what: via
        where:
          ref: matrix_inner_home
          shift: [reset_shift_x,reset_shift_y+5]
        params:
          net: GND

      via2:
        what: via
        where:
          ref: matrix_inner_home
          shift: [battery_shift_x+3,battery_shift_y]
        params:
          net: GND

      via3:
        what: via
        where:
          ref: matrix_inner_home
          shift: [slider_shift_x-4,slider_shift_y+2]
        params:
          net: BAT_P

      via4:
        what: via
        where:
          ref: matrix_inner_home
          shift: [slider_shift_x-4,slider_shift_y-1]
        params:
          net: RAW

      via5:
        what: via
        where:
          ref: matrix_inner_home
          shift: [battery_shift_x-4,battery_shift_y-4]
        params:
          net: BAT_P



      right_cover_hole:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [thumbs_inner]
          shift: [.3kx, .8ky]

      left_cover_hole:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [thumbs_inner]
          shift: [-.7kx, .8ky]


      #need to widen pcb holes to fit standoffs!
      hole_top_left:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_pinky_top]
          shift: [.675kx,0]
        params:
          hole_size: '5'
          hole_drill: '5'

      hole_top_right:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_index_top]
          shift: [.5kx,-.5ky]
        params:
          hole_size: '5'
          hole_drill: '5'

      hole_bottom_right:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_pinky_home]
          shift: [.62kx,-.1ky]
        params:
          hole_size: '5'
          hole_drill: '5'

      hole_bottom_left:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_middle_bottom]
          shift: [0,-1.1ky]
        params:
          hole_size: '5'
          hole_drill: '5'

      hole_thumbs:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [thumbs_main]
          shift: [.575kx,-.1kx]
        params:
          hole_size: '5'
          hole_drill: '5'

  case_blueprint:
    outlines:
      main:
        outline: case_top_plate

    footprints:
      right_cover_hole:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [thumbs_inner]
          shift: [.3kx, .8ky]

      left_cover_hole:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [thumbs_inner]
          shift: [-.7kx, .8ky]

      hole_top_left:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_pinky_top]
          shift: [.675kx,0]

      hole_top_right:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_index_top]
          shift: [.5kx,-.5ky]

      hole_bottom_right:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_pinky_home]
          shift: [.62kx,-.1ky]

      hole_bottom_left:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_middle_bottom]
          shift: [0,-1.1ky]

      hole_thumbs:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [thumbs_main]
          shift: [.575kx,-.1kx]