metadata:
  engine: 4.0.2
  keyboard: Splayer 1
  version: 1.0
  author: Yoragon

units:
  # Proxy spacing variables
  kx: cx
  ky: cy
  # Padding variables
  px: kx + 3
  py: ky + 3
  # Adjusting preview to choc keys
  $default_width: cx
  $default_height: cy

  # Stagger values used in the matrix
  ring_stagger: 2
  matrix_stagger: 5

  # Splay values used in the matrix
  pinky_splay: 10
  ring_splay: -8
  nullify_splay: -(ring_splay+pinky_splay)
  thumb_splay: -12

  # Spread values used in the matrix
  pinky_ring_spread: kx+2
  ring_middle_stagger: kx+1

  # Shift value of the controller
  controller_shift_x: kx+3.25
  controller_shift_y: 8
  # Shift value of the battery plug
  battery_shift_x: kx+3.25
  battery_shift_y: -10
  # Shift value of the reset button
  reset_shift_x: kx+10
  reset_shift_y: -20
  # Shift value of the slider switch
  slider_shift_x: kx+12.5
  slider_shift_y: -30

points:
  key:
    # Choc spacing
    padding: ky
    spread: kx

  zones:
    # Primary 3x5 key matrix
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      columns:
        pinky:
          key:
            bind: 0
            splay: pinky_splay
          rows:
              top:
                column_net: P1
              home:
                column_net: P3
              bottom:
                column_net: P6

        ring:
          key:
            splay: ring_splay
            spread: pinky_ring_spread
            stagger: ring_stagger
          rows:
            top:
              column_net: P0
            home:
              column_net: P4
            bottom:
              column_net: P7

        middle:
          key:
            stagger: matrix_stagger
            splay: nullify_splay
            spread: ring_middle_stagger
          rows:
            top:
              column_net: P2
            home:
              column_net: P5
            bottom:
              column_net: P8

        index:
          key:
            stagger: -matrix_stagger
          rows:
            top:
              column_net: P21
            home:
              column_net: P19
            bottom:
              column_net: P15

        inner:
          key:
            stagger: -matrix_stagger
          rows:
            top:
              column_net: P20
            home:
              column_net: P18
            bottom:
              column_net: P14

      rows:
        bottom:
        home:
        top:

    # Thumb cluster keys
    thumbs:
      # The thumb cluster is anchored to the bottom left, though it is shifted such that the middle key of the cluster is placed under the inner column of the main matrix
      anchor:
        ref: matrix_inner_bottom
        shift: [-kx-3,-ky]

      columns:
        outer:
          key:
            column_net: P9

        main:
          key:
            bind: [0,0,0,3]
            splay: thumb_splay
            shift: [3,-2]
            column_net: P16

        inner:
          key:
            splay: thumb_splay
            shift: [6,-3]
            column_net: P10

outlines:
  keys_outline:
    - what: rectangle
      where: true
      size: [px, py]
      bound: true

  keys:
    - what: rectangle
      where: true
      size: [kx, ky]

  switch_hole:
    - what: rectangle
      where: true
      size: [13.95, 13.95]

  polygon:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_pinky_top
          shift: [0.5px,0.5py]
        - ref: matrix_inner_top
          shift: [1.55px,0.5py]
        - ref: thumbs_inner
          shift: [0.5px,0.5py]
        - ref: thumbs_outer
          shift: [-0.5px,-0.5py]
        - ref: thumbs_outer
          shift: [-0.5px,0.21py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]

  board:
    - name: keys_outline
    - operation: add
      name: polygon
      fillet: 1.9

  case_top_plate:
    - name: board
    - operation: subtract
      name: switch_hole

pcbs:
  splayer_pcb:
    outlines:
      main:
        outline: board

    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: GND

      choc:
        what: choc
        where: true
        adjust:
          rotate: 180
        params:
          keycaps: true
          reverse: true
          from: "{{column_net}}"
          to: GND

      controller:
        what: promicro_pretty
        where:
          ref: matrix_inner_home
          shift: [controller_shift_x,controller_shift_y]
          rotate: -90

      front_battery:
        what: jstph
        params:
          side: "F"
          pos: pos
          neg: GND
        where:
          ref: matrix_inner_home
          shift: [battery_shift_x,battery_shift_y]
          rotate: 0

      back_battery:
        what: jstph
        params:
          side: "B"
          pos: pos
          neg: GND
        where:
          ref: matrix_inner_home
          shift: [battery_shift_x,battery_shift_y]
          rotate: 0

      front_reset:
        what: button
        params:
          side: "F"
          from: RST
          to: GND
        where:
          ref: matrix_inner_home
          shift: [reset_shift_x,reset_shift_y]
          rotate: 90

      back_reset:
        what: button
        params:
          side: "B"
          from: RST
          to: GND
        where:
          ref: matrix_inner_home
          shift: [reset_shift_x,reset_shift_y]
          rotate: 90

      front_slider:
        what: slider
        params:
          side: "F"
          from: pos
          to: RAW
        where:
          ref: matrix_inner_home
          shift: [slider_shift_x,slider_shift_y]
          rotate: -90

      back_slider:
        what: slider
        params:
          side: "B"
          from: pos
          to: RAW
        where:
          ref: matrix_inner_home
          shift: [slider_shift_x,slider_shift_y]
          rotate: -90

      hole_top_left:
        what: mountinghole
        where:
          ref: [matrix_pinky_top]
          shift: [.675kx,0]

      hole_top_right:
        what: mountinghole
        where:
          ref: [matrix_index_top]
          shift: [.5kx,-.5ky]

      hole_bottom_right:
        what: mountinghole
        where:
          ref: [matrix_ring_bottom]
          shift: [0,-.75ky]

      hole_bottom_left:
        what: mountinghole
        where:
          ref: [matrix_index_bottom]
          shift: [0,-.65ky]

      hole_thumbs:
        what: mountinghole
        where:
          ref: [thumbs_main]
          shift: [.55kx,-.5]

  case_blueprint:
    outlines:
      main:
        outline: case_top_plate

    footprints:
      hole_top_left:
        what: mountinghole
        where:
          ref: [matrix_pinky_top]
          shift: [.675kx,0]

      hole_top_right:
        what: mountinghole
        where:
          ref: [matrix_index_top]
          shift: [.5kx,-.5ky]

      hole_bottom_right:
        what: mountinghole
        where:
          ref: [matrix_ring_bottom]
          shift: [0,-.75ky]

      hole_bottom_left:
        what: mountinghole
        where:
          ref: [matrix_index_bottom]
          shift: [0,-.65ky]

      hole_thumbs:
        what: mountinghole
        where:
          ref: [thumbs_main]
          shift: [.55kx,-.5]

#cases:
#  bottom:
#    what: board
#    extrude: 1
